In [90]:
import numpy as np

In [22]:
observed = np.random.randint(low=0, high=2, size=10)
observed

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0])

In [23]:
actual = np.random.random(size=10)
actual

array([0.58201345, 0.00139984, 0.1229833 , 0.00232826, 0.34504348,
       0.68879666, 0.18594908, 0.371802  , 0.82917496, 0.34330433])

In [24]:
-np.sum(observed * np.log(actual) + (1 - observed) * np.log(1.0 - actual))

18.50759700121238

In [30]:
observed = np.random.randint(low=0, high=2, size=10)
observed

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 1])

In [39]:
actual = np.array([0.999, 0.001, 0.001, 0.002, 0.99, 0.998, 0.001, 0.002, 0.99, 0.99])
actual

array([0.999, 0.001, 0.001, 0.002, 0.99 , 0.998, 0.001, 0.002, 0.99 ,
       0.99 ])

In [40]:
-np.sum(observed * np.log(actual) + (1 - observed) * np.log(1.0 - actual))

0.04015901690685773

In [86]:
observed = np.random.randint(low=0, high=2, size=10)
observed

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1])

In [87]:
actual = np.random.randint(low=0, high=2, size=10)
actual

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [89]:
np.sum(actual == actual) / 10

1.0

In [91]:
a = [1, 2, 3, 4, 5]

In [108]:
np.roll(a, shift=np.random.randint(0, len(a))).tolist()

[4, 5, 1, 2, 3]

In [109]:
actual

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 0])